### ISSUE TITLE
This repository should not be public

### ISSUE THREAD

**Issue by skearnes** [KyleAMathews/stanford-2-ward-app#1]
This data is not public; please make this repository private ASAP.

**Comment by skearnes** [comment]
FYI if you need someone with a paid account to host private repos, you could transfer ownership to me: https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/

**Comment by KyleAMathews** [comment]
Is there any reason to keep this around? I can just delete the account.

**Comment by skearnes** [comment]
No idea; did you pass this on to someone else in the ward?

**Comment by skearnes** [comment]
I'm guessing that if you're not working on this anymore, nobody will.

**Comment by KyleAMathews** [comment]
I was helping Adam with it — but don't think it was ever used 🤷‍♂️ I'll just delete it.
